# Developer module config — inherits global
inherits: "{project-root}/_kratos/_config/global.yaml"

module_name: "dev"
module_version: "1.0.2"

agents_path: "{project-root}/_kratos/dev/agents"
skills_path: "{project-root}/_kratos/dev/skills"
knowledge_path: "{project-root}/_kratos/dev/knowledge"
skill_index: "{project-root}/_kratos/dev/skills/_skill-index.yaml"
